---

- name: Install MongoDB
  
  hosts: db
  gather_facts: yes
  # Admin access 
  become: true
  
  
  tasks:
  - name: Import the MongoDB public key
    ansible.builtin.apt_key:
      url: https://www.mongodb.org/static/pgp/server-7.0.asc
      state: present

  - name: Add the MongoDB repository
    ansible.builtin.apt_repository:
      repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
      state: present
      update_cache: yes

  - name: Install MongoDB 7.0.6
    ansible.builtin.apt:
      name: mongodb-org=7.0.6
      state: enable
 

  - name: Enable MongoDB service to start on boot
    service:
      name: mongod
      state: started
      enabled: true 
