# starts with ---
---

- name: Provision app vm
  # Where to run this playbook
  hosts: web

  # get comprehensive facts on the hosts
  gather_facts: yes

  # do we need admin access - use sudo
  become: true
      
  # instructions aka tasks
  tasks:
    # CLONE APP
  - name: Clone the app repository to the controller node      
    delegate_to: localhost
    ansible.builtin.git:
      repo: 'https://github.com/shonifari/tech264-sparta-app.git'
      dest: /home/{{ ansible_user }}/repo
      version: main


  - name: Update apt repository and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Install NodeSource Node.js 20.x repository
    ansible.builtin.shell: |
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  
  - name: Install Node.js and npm
    apt:
      name:
        - nodejs
      state: present

  - name: Verify Node.js version
    ansible.builtin.command: node -v
    register: node_version

  - name: Print Node.js version
    ansible.builtin.debug:
      msg: "Node.js version is {{ node_version.stdout }}"


    # Copy app
  - name: Copy app folder to target node      
    ansible.builtin.copy:
        src: /home/{{ ansible_user }}/repo/
        dest: /home/{{ ansible_user }}/repo/
        mode: '0755'

  - name: Install packages based on package.json.
    community.general.npm:
      path: /home/{{ ansible_user }}/repo/app/

  - name: Start the application using PM2
    shell: npm start
    args:
      chdir: /home/{{ ansible_user }}/repo/app