# Create a new playbook named prov-db.yml. This playbook should to do install/configure the database on the database VM:
# Install Mongo DB v7.0.6
# Allow connections to database from 127.0.0.1 to 0.0.0.0
# Restart and enable Mongo DB
# From the Ansible controller, run adhoc commands to:
# Check the status of the database to make sure it's running
# Check the bindIp has been configured

---

- name: Provision DB 

  hosts: db
  gather_facts: yes
  # Admin access 
  become: true
  
  
  tasks:

  # Install MongoDB
  - name: Import the MongoDB public key
    ansible.builtin.apt_key:
      url: https://www.mongodb.org/static/pgp/server-7.0.asc
      state: present

  - name: Add the MongoDB repository
    ansible.builtin.apt_repository:
      repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
      state: present
      update_cache: yes

  - name: Install MongoDB 7.0.6
    ansible.builtin.apt:
      name: mongodb-org=7.0.6
      state: present

  # Restart MongoDB
  - name: Enable MongoDB service to start on boot
    service:
      name: mongod
      state: started
      enabled: true 

  # Configure MongoDB
  # Allow connections to database from 127.0.0.1 to 0.0.0.0

  - name: Configure MongoDB to allow connections from any IP
    lineinfile:
      path: /etc/mongod.conf
      regexp: '^  bindIp:'
      line: '  bindIp: 0.0.0.0'
      insertafter: '^# network interfaces'
      
  # Restart Nginx
  - name: restart mongodb
    service:
      name: mongod
      state: restarted


# ansible db  -a "sudo systemctl status nginx"
# ansible db  -a "grep 'bindIp' /etc/mongod.conf"